version: '3.8'

services:
  php:
    image: php:7.0-apache  # PHP 7.0 image
    container_name: php_app
    volumes:
      - ./php-login:/var/www/html
    ports:
      - "8000:80"

  aspnet:
    image: mcr.microsoft.com/dotnet/aspnet:8.0 # Using asp.net core 8.0
    container_name: aspnet_app
    volumes:
      - ./aspnet-login:/app
    ports:
      - "8080:80"
    entrypoint: ["dotnet", "aspnet-login.dll"]
