version: '3.8'

services:
  php:
    build: ./php
    container_name: php_app
    volumes:
      - ./php-login:/var/www/html
    ports:
      - "8000:80"

  aspnet:
    build: ./aspnet
    container_name: aspnet_app
    volumes:
      - ./aspnet-login:/app
    ports:
      - "8080:80"
