version: '3.8'

services:
  php:
    image: php:7.0-apache  # PHP 7.0 image
    container_name: php_app
    volumes:
      - ./php-login:/var/www/html
    ports:
      - "8000:80"

  aspnet:
    build: ./aspnet-login
    container_name: aspnet_app
    ports:
      - "8080:8080"
