version: '3.8'
services:
  php:
    image: php:8.1-apache
    container_name: php_app
    volumes:
      - ./php-login:/var/www/html
    ports:
      - "8080:80"
  aspnet:
    image: mcr.microsoft.com/dotnet/aspnet:7.0
    container_name: aspnet_app
    volumes:
      - ./aspnet-login:/app
    ports:
      - "8081:80"
